services:
  - type: web
    name: retrobingo
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_PATH
        value: /tmp/retrobingo.db
